# Generated by Django 5.1 on 2024-08-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='played_at',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player',
        ),
    ]
